# Generated by Django 3.0.4 on 2020-07-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(max_length=100)),
                ('app_name', models.CharField(max_length=50)),
                ('app_icon', models.ImageField(upload_to='image/')),
                ('developer_name', models.CharField(max_length=50)),
                ('no_of_downloads', models.CharField(max_length=50)),
                ('app_rating', models.CharField(max_length=50)),
                ('no_of_reviews', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWordData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('app_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app_search.AppInfo', verbose_name='Category')),
            ],
        ),
    ]
