# Generated by Django 3.0.4 on 2020-04-16 03:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200416_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 16, 3, 0, 48, 845703, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
