# Generated by Django 3.0.4 on 2020-04-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userdata_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_image',
            field=models.ImageField(blank=True, default='logo6.png', null=True, upload_to='profile_image/'),
        ),
    ]
